name: CI

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - 'release-please--**'

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    container: node:24-bookworm-slim
    steps:
      - uses: actions/checkout@v4
      - run: npm ci
      - run: npm run check
      - run: npm run typecheck
      - run: npm test
      - run: npm pack --dry-run
